# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
 - name: generate-sitemap
  # You may pin to the exact commit or the version.
  # uses: cicirello/generate-sitemap@cf969bce72d620ade9964831a9e82b1404f7a342
  uses: cicirello/generate-sitemap@v1.8.1
  with:
    # The path to the root of the website
    path-to-root: # optional, default is .
    # The url of your webpage
    base-url-path: # optional, default is https://web.address.of.your.nifty.website/
    # Indicates whether to include html files in the sitemap.
    include-html: # optional, default is true
    # Indicates whether to include pdf files in the sitemap.
    include-pdf: # optional, default is true
    # Indicates if sitemap should be formatted in xml.
    sitemap-format: # optional, default is xml
    # Space separated list of additional file extensions to include in sitemap.
    additional-extensions: # optional, default is 
    # Enables dropping .html from urls in sitemap.
    drop-html-extension: # optional
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.


